config/routes.rb
Rails.application.routes.draw do
  resources :tipos
  resources :products do 
    collection do 
      get :csv
      get :pdf
    end
  end
  root 'products#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :tipo
    validates :name, :description, :price, presence: true
end

app/models/tipo.rb
class Tipo < ApplicationRecord
    has_many :product
    validates :name, :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
require './app/reportes/product_csv.rb'
require './app/reportes/product_pdf.rb'
class ProductsController < ApplicationController
    def index
        @products = Product.all  
    end

    def new
        @product = Product.new  
    end

    def create
        @product = Product.new(params_product)
        if @product.save
            redirect_to products_path
        else
            render :new
        end
    end

    def edit
        @product = Product.find(params[:id])
    end

    def update
        @product = Product.find(params[:id])
        if @product.update(params_product)
            redirect_to products_path
        else
            render :edit
        end
    end

    def destroy
        @product = Product.find(params[:id])
        @product.destroy
        redirect_to products_path
    end

    def csv
        send_data ProductCsv.new.call,
        :type => 'text/csv; charset=iso-8859-1; header=present',
        :disposition => "attachment; filename=productos.csv"
    end

    def pdf

        pdf = ProductPdf.new.call
        send_data pdf.render,
            filename: "export.pdf",
            type: 'application/pdf',
            disposition: 'inline'

    end
        
    private
        def params_product
            params.require(:product).permit(:name, :description, :price, :tipo_id.name)
        end

end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController
    
    def index
        @tipos = Tipo.all
    end

    def new
        @tipo = Tipo.new
    end

    def create
        @tipo = Tipo.new(params_tipo)
        if @tipo.save
            redirect_to tipos_path
        else
            render :new
        end
    end

    def edit
        @tipo = Tipo.find(params[:id])
    end

    def update
        @tipo = Tipo.find(params[:id])
        if @tipo.update(params_tipo)
            redirect_to tipos_path
        else
            render :edit
        end
    end

    def destroy
        @tipo = Tipo.find(params[:id])
        @tipo.destroy
        redirect_to tipos_path
    end

    private
        def params_tipo
            params.require(:tipo).permit(:name, :description)
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Almacen Manuel</h1>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<%= form_for @product do |f|%>
    <div>
        <%= f.label :Nombre%>
        <%= f.text_field :name%>
    </div>
    <div>
        <%= f.label :Descripcion%>
        <%= f.text_area :description%>
    </div>
    <div>
        <%= f.label :Precio%>
        <%= f.number_field :price%>
    </div>
    <div>
        <%= f.label :Tipo%>
        <p>
            <%= f.collection_select(:tipo_id, Tipo.all, :id, :name) %>
        </p>
    </div>
    <div>
        <p><%= f.submit%></p>
    </div>
    <p><%= link_to "Regresar", products_path%></p>
<%end%>

app/views/products/index.html.erb
<h2>Listado de Productos</h2>

<p><%= link_to "Tipos de productos", tipos_path%></p>
<p><%= link_to "Agregar", new_product_path%></p>

<table>
    <tr>
        <thead>
            <th>Nombre</th>
            <th>Descripcion</th>
            <th>Precio</th>
            <th>Tipo</th>
            <th>Accion</th>
        </thead>
    </tr>
    <% @products.each do |product| %>
        <tr>
            <td><%= product.name %></td>
            <td><%= product.description %></td>
            <td><%= product.price %></td>
            <td><%= product.tipo.name%></td>
            <td>
                <%= link_to "Editar", edit_product_path(product)%>
                <%= link_to "Eliminar", product, method: :delete, data: {confirm: "Desea eliminar este registro?"} %>
            </td>
        </tr>
    <%end%>

</table>
<br><br>


<p><%= link_to "Imprimir CSV",  {:action=>'csv'} %></p>
<p><%= link_to "Imprimir PDF",  {:action=>'pdf'}%></p>

app/views/products/new.html.erb
<%= form_for @product do |f|%>
    <div>
        <%= f.label :Nombre%>
        <%= f.text_field :name%>
    </div>
    <div>
        <%= f.label :Descripcion%>
        <%= f.text_area :description%>
    </div>
    <div>
        <%= f.label :Precio%>
        <%= f.number_field :price%>
    </div>
    <div>
        <p><%=f.label :Tipo%></p>
        <p>
            <%= f.collection_select(:tipo_id, Tipo.all, :id, :name) %>
        </p>
    </div>

    <div>
        <p><%= f.submit%></p>
    </div>
    <p><%= link_to "Regresar", products_path%></p>
<%end%>

app/views/tipos/edit.html.erb
<%= form_for @tipo do |f|%>
    <div>
        <%= f.label :Nombre%>
        <%= f.text_field :name%>
    </div>
    <div>
        <%= f.label :Descripcion%>
        <%= f.text_area :description%>
    </div>
    <div>
        <p><%= f.submit%></p>
    </div>
    <p><%= link_to "Regresar", tipos_path%></p>
<%end%>

app/views/tipos/index.html.erb
<h2>Tipo de Productos</h2>
<p><%= link_to "Productos", products_path%></p>
<p><%= link_to "Agregar", new_tipo_path%></p>
<table>
    <tr>
        <thead>
            <th>Nombre</th>
            <th>Descripcion</th>
            <th>Accion</th>
        </thead>
    </tr>
    <% @tipos.each do |tipo| %>
        <tr>
            <td><%= tipo.name %></td>
            <td><%= tipo.description %></td>
            <td>
                <%= link_to "Editar", edit_tipo_path(tipo)%>
                <%= link_to "Eliminar", tipo, method: :delete, data: {confirm: "Desea eliminar este registro?"} %>
            </td>
        </tr>
    <%end%>
</table>

app/views/tipos/new.html.erb
<%= form_for @tipo do |f|%>
    <div>
        <%= f.label :Nombre%>
        <%= f.text_field :name%>
    </div>
    <div>
        <%= f.label :Descripcion%>
        <%= f.text_area :description%>
    </div>
    <div>
        <p><%= f.submit%></p>
    </div>
    <p><%= link_to "Regresar", tipos_path%></p>
<%end%>